namespace: rabbitmq

stack:
  defines: process-group
  runnable-list:
    - rabbitmq/rabbitmq
    - rabbitmq/nginx
  variables:
    rabbitmq-image-tag: "3.10-management"
    nginx-listen-port: 8080
    nginx-image-tag: "latest"